# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMsa3xnh89cQ6yK6n0NISLyWUHMc5yDl
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

"""READING THE DATAFILE"""

df = pd.read_csv("/content/housing.csv")

print(df)

print(df.shape)

print(df.head(10))

print(df.tail(10))

print(df.columns)

print(df['total_rooms'])

X = df['total_rooms'].head(150).values.reshape(-1,1)

y = df['median_house_value'].head(150).values.reshape(-1, 1)

plt.ylabel("Median House Value")

plt.scatter(X, y)

plt.title("Scatter Plot of Total Rooms vs. Median House Value")
plt.show()

print(df.describe())

